notifications:
  email: false
dist: trusty
sudo: false
group: beta
language: node_js
cache:
  directories:
  - "$HOME/.npm"
jobs:
- stage: NPM release
  if: tag IS present
  script: echo 'Deploying to NPM...'
  before_deploy:
  - npm run build
  deploy:
    provider: npm
    email: chadima.jiri@gmail.com
    skip_cleanup: true
    api_key: "$NPM_TOKEN"
    on:
      repo: fragaria/angular-daterangepicker
      tags: true
env:
  global:
    secure: RHSF+oiH8IhPvTvK/Cx3WhAK3lHISDg3wdYgqJRi6EpgaYFcoiPWz540Gw3R9o0Zx58ux0xTs1MYRqFqyqA/5KMdhMw/ICyuiM3BtC6TrglDVzBtcfIwBk6dy9QzffAVvmwgeXkk6vJBVpHcB6VVuQxdsHm1B8+pm/ibr0UpFxw=
